name: Storybook Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
            cache: 'yarn'
      - name: restore lerna
        uses: actions/cache@v3
        id: cache-lerna
        with:
          path: |
            '**/node_modules'
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-lerna.outputs.cache-hit != 'true'
        run: yarn
      - name: Build helepr
        run: yarn build
        working-directory: ./packages/helper
      - name: Run Storybook tests
        run: yarn test:ci
        working-directory: ./packages/react-moveable
      - name: Run Original Storybok
        if: ${{ failure() }}
        run: yarn test:fail-ci
        working-directory: ./packages/react-moveable
      - name: Archive Failed Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed snapshot
          path: packages/react-moveable/__snapshots__


