name: Storybook Tests
on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
            cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run Storybook tests
        run: yarn test:ci
        working-directory: ./packages/react-moveable
      - name: Run Original Storybok
        if: ${{ failure() }}
        run: yarn test:fail-ci
        working-directory: ./packages/react-moveable
      - name: Archive Failed Artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: failed snapshot
          path: packages/react-moveable/__snapshots__


